name: docs

on:
  push:
    branches:
      - main
  pull_request:

# security: restrict permissions for CI jobs.
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
        timeout-minutes: 2
        continue-on-error: true
      - name: Install maturin[zig] from PyPI
        uses: install-pinned/maturin-with-zig@6d6efe60fc7e0aaab814eb56cc251fc611367dd8
      - name: Install mypy from PyPI
        uses: install-pinned/mypy@75779f141592e4909d64e13f8a1861f06aa9cd8d
      - name: Install pdoc from PyPI
        uses: install-pinned/pdoc@69ba59f9699df21e1026110af4ec6b10a98cf5cd

      - run: maturin build
        working-directory: ./mitmproxy-rs
      - run: pip install --no-index --find-links target/wheels/ mitmproxy_rs

      - run: stubtest --allowlist mitmproxy-rs/stubtest-allowlist.txt --mypy-config-file mitmproxy-rs/pyproject.toml mitmproxy_rs

      - run: pdoc -o docs/ mitmproxy_rs

      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v5
